import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import 'vuetify/styles'

export default createVuetify({
  components,
  directives,
  icons: {
    defaultSet: 'mdi',
    aliases,
    sets: {
      mdi,
    },
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        colors: {
          primary: '#00606d',
          primarycontainer: '#007b8b',
          secondary: '#006a63',
          secondarycontainer: '#8bf1e6',
          tertiary: '#005c8d',
          tertiarycontainer: '#0375b2',
          surface: '#f7fafb',
          surfacevariant: '#e0e3e4',
          background: '#f7fafb',
          error: '#ba1a1a',
          errorcontainer: '#ffdad6',
          onprimary: '#ffffff',
          onprimarycontainer: '#dff9ff',
          onsecondary: '#ffffff',
          onsecondarycontainer: '#006f67',
          ontertiary: '#ffffff',
          ontertiarycontainer: '#edf5ff',
          onsurface: '#181c1d',
          onsurfacevariant: '#3e494b',
          onbackground: '#181c1d',
          onerror: '#ffffff',
          onerrorcontainer: '#93000a',
          inversesurface: '#2d3132',
          inverseonurface: '#eef1f2',
          inverseprimary: '#7ad4e5',
          outline: '#6e797b',
          outlinevariant: '#bdc8cb',
          shadow: '#000000',
          scrim: '#000000',
        },
      },
      dark: {
        colors: {
          primary: '#8bf1e6',
          primarycontainer: '#004e59',
          secondary: '#71d7cd',
          secondarycontainer: '#00504a',
          tertiary: '#94ccff',
          tertiarycontainer: '#004b74',
          surface: '#181c1d',
          surfacevariant: '#3e4647',
          background: '#181c1d',
          error: '#ffb4ab',
          errorcontainer: '#93000a',
          onprimary: '#00363d',
          onprimarycontainer: '#a0efff',
          onsecondary: '#00201d',
          onsecondarycontainer: '#8ef4e9',
          ontertiary: '#001d32',
          ontertiarycontainer: '#cde5ff',
          onsurface: '#e0e3e4',
          onsurfacevariant: '#bfc8ca',
          onbackground: '#e0e3e4',
          onerror: '#690005',
          onerrorcontainer: '#ffdad6',
          inversesurface: '#e0e3e4',
          inverseonurface: '#2d3132',
          inverseprimary: '#00606d',
          outline: '#5e6566',
          outlinevariant: '#3e4647',
          shadow: '#000000',
          scrim: '#000000',
        },
      },
    },
  },
})
